export const personas = [
  { persona_Id: 1, name: "AINTZANE VILLALOBOS", color: "#FFD54F", email: "aintzanev@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 2, name: "AITOR TECEDOR", color: "#81C784", email: "aitort@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 3, name: "ALBA ARANGUREN", color: "#64B5F6", email: "alba@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 4, name: "ALMUDENA MAESTRE", color: "", email: "almudena@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 5, name: "AMANDA NEIRA", color: "", email: "amanda@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 6, name: "ANA MARIA MARTIN", color: "", email: "anamaria@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 7, name: "ANE LOPEZ", color: "", email: "ane@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 8, name: "ARANTZA ARRATIBEL", color: "", email: "arantzaa@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 9, name: "ARANTZA VÁZQUEZ", color: "", email: "arantzav@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 10, name: "ARITZ MANCHADO", color: "", email: "aritzm@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 11, name: "BAKARTXO LOPEZ", color: "", email: "bakartxo@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 12, name: "CARLOS ASENSIO", color: "", email: "carlosa@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 13, name: "CAROLINA FERNANDEZ", color: "", email: "erroak@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 14, name: "CENTRO EMPLEO", color: "", email: "centroempleo@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 15, name: "ELENA ANSOALDE", color: "", email: "elenaa@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 16, name: "EMPLEO ERROAK", color: "", email: "empleo@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 17, name: "ESMERALDA ROMAN", color: "", email: "esmeralda@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 18, name: "ESTIBALIZ ZUGASTI", color: "", email: "ezugasti@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 19, name: "ETOR CARRO", color: "", email: "etorc@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 20, name: "EVA VIRTO", color: "", email: "evav@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 21, name: "GARBIÑE CARTON", color: "", email: "garbine@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 22, name: "HARRERA ERROAK", color: "", email: "harrera@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 23, name: "IDOYA ARTEAGA", color: "", email: "idoya@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 24, name: "IÑAKI LOPE", color: "", email: "lope@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 25, name: "IRATI MAÑERU", color: "", email: "irati@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 26, name: "IRATXE BEOBIDE", color: "", email: "iratxe@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 27, name: "IVALIN DIMITROV", color: "", email: "ivalind@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 28, name: "IZASKUN JIMENEZ", color: "", email: "izaskun@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 29, name: "JONE KRUZELEGI", color: "", email: "jonek@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 30, name: "KIEL RICO", color: "", email: "kiel@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 31, name: "LIERNI ESNAOLA", color: "", email: "liernie@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 32, name: "MAIALEN AROCENA", color: "", email: "maialena@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 33, name: "MAITE ARRETXE", color: "", email: "maite@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 34, name: "MAMEN PAJARES", color: "", email: "mamenp@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 35, name: "MARIVI SAN JUAN", color: "", email: "marivis@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 36, name: "MARKEL LAZARO", color: "", email: "markel@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 37, name: "MIKEL ZUMETA", color: "", email: "mikelz@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 38, name: "MIREN GARCIA", color: "", email: "miren@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 39, name: "NATALIA GONZALEZ", color: "", email: "nataliag@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 40, name: "NEREA AMUNARRIZ", color: "", email: "nereaa@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 41, name: "NICOLETA LOIDI", color: "", email: "nicoletal@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 42, name: "NURIA RUIZ", color: "", email: "nuriarc@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 43, name: "OIHANA MERINO", color: "", email: "oihana@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 44, name: "PEPE LAZARO", color: "", email: "martutene@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 45, name: "PILAR SANSUAN", color: "", email: "pilars@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 46, name: "RAQUEL RUIZ", color: "", email: "raquelr@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 47, name: "ROSA ARANDIA", color: "", email: "arandia@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 48, name: "ROSA OYARZABAL", color: "", email: "rosao@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 49, name: "SHANTI IRIBAR", color: "", email: "shanti@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 50, name: "SONIA TOBIA", color: "", email: "sonia@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 51, name: "SUSANA CARRANZA", color: "", email: "susanac@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 52, name: "TERESA MOREDA", color: "", email: "teresam@erroak.sartu.org", contraseña: "Erro@k2025" , movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: ""},
  { persona_Id: 53, name: "TXELO BERRA", color: "", email: "txelobe@erroak.sartu.org", contraseña: "Erro@k2025", movil: "", extension: "", centro_id: "", llave: true, alarma: true, turno_trabajo: "" }
];

export const espacios = [
    { espacio_Id: 1, espacio: "AMARA DESPACHO 0" },
    { espacio_Id: 2, espacio: "AMARA DESPACHO 1" },
    { espacio_Id: 3, espacio: "AMARA DESPACHO 2" },
    { espacio_Id: 4, espacio: "AMARA DESPACHO 3" },
    { espacio_Id: 5, espacio: "AMARA DESPACHO 4" },
    { espacio_Id: 6, espacio: "AMARA DESPACHO 5" },
    { espacio_Id: 7, espacio: "AMARA DESPACHO 6" },
    { espacio_Id: 8, espacio: "AMARA DESPACHO 7" },
    { espacio_Id: 9, espacio: "AMARA DESPACHO 8" },
    { espacio_Id: 10, espacio: "AMARA CENTRO EMPLEO" },
    { espacio_Id: 11, espacio: "AMARA AULA INFORMATICA" },
    { espacio_Id: 12, espacio: "MARTUTENE 12 AULA INFORMÁTICA" },
    { espacio_Id: 13, espacio: "MARTUTENE 12 ELKARREKIN" },
    { espacio_Id: 14, espacio: "MARTUTENE 12 EMARI" },
    { espacio_Id: 15, espacio: "MARTUTENE 12 AURRERA" },
    { espacio_Id: 16, espacio: "MARTUTENE 30 DESPACHO 1" },
    { espacio_Id: 17, espacio: "MARTUTENE 30 DESPACHO 2" },
    { espacio_Id: 18, espacio: "MARTUTENE 30 AULA INFORMÁTICA" },
    { espacio_Id: 19, espacio: "MARTUTENE 30 AULA 1" },
    { espacio_Id: 20, espacio: "MARTUTENE 30 AULA 2" },
    { espacio_Id: 21, espacio: "MARTUTENE 30 SUKALDEA" },
    { espacio_Id: 22, espacio: "MARTUTENE 30 SOCIOSANITARIO" },
    { espacio_Id: 23, espacio: "MARTUTENE 30 CENTRO DE DÍA" },
    { espacio_Id: 24, espacio: "MARTUTENE 30 BIDEAN" },
    { espacio_Id: 25, espacio: "MARTUTENE 30 TABERNA" },
    { espacio_Id: 26, espacio: "MARTUTENE 30 ITURGINTZA" },
    { espacio_Id: 27, espacio: "MARTUTENE 30 SOLDADURA" },
    { espacio_Id: 28, espacio: "AMARA DESPACHO 0 TARDE" },
    { espacio_Id: 29, espacio: "AMARA DESPACHO 1 TARDE" },
    { espacio_Id: 30, espacio: "AMARA DESPACHO 2" },
    { espacio_Id: 31, espacio: "AMARA DESPACHO 3" },
    { espacio_Id: 32, espacio: "AMARA DESPACHO 4" },
    { espacio_Id: 33, espacio: "AMARA DESPACHO 5" },
    { espacio_Id: 34, espacio: "AMARA DESPACHO 6" },
    { espacio_Id: 35, espacio: "AMARA DESPACHO 7" },
    { espacio_Id: 36, espacio: "AMARA DESPACHO 8" },
    { espacio_Id: 37, espacio: "AMARA CENTRO EMPLEO" },
    { espacio_Id: 38, espacio: "AMARA AULA INFORMATICA" },
    { espacio_Id: 39, espacio: "MARTUTENE 12 AULA INFORMÁTICA" },
    { espacio_Id: 40, espacio: "MARTUTENE 12 ELKARREKIN" },
    { espacio_Id: 41, espacio: "MARTUTENE 12 EMARI" },
    { espacio_Id: 42, espacio: "MARTUTENE 12 AURRERA" },
    { espacio_Id: 43, espacio: "MARTUTENE 30 DESPACHO 1" },
    { espacio_Id: 44, espacio: "MARTUTENE 30 DESPACHO 2" },
    { espacio_Id: 45, espacio: "MARTUTENE 30 AULA INFORMÁTICA" },
    { espacio_Id: 46, espacio: "MARTUTENE 30 AULA 1" },
    { espacio_Id: 47, espacio: "MARTUTENE 30 AULA 2" },
    { espacio_Id: 48, espacio: "MARTUTENE 30 SUKALDEA" },
    { espacio_Id: 49, espacio: "MARTUTENE 30 SOCIOSANITARIO" },
    { espacio_Id: 50, espacio: "MARTUTENE 30 CENTRO DE DÍA" },
    { espacio_Id: 51, espacio: "MARTUTENE 30 BIDEAN" },
    { espacio_Id: 52, espacio: "MARTUTENE 30 TABERNA" },
    { espacio_Id: 53, espacio: "MARTUTENE 30 ITURGINTZA" },
    { espacio_Id: 54, espacio: "MARTUTENE 30 SOLDADURA" }
]

export const programas = [
    { programa_Id: 1, programa: "LANBIDE"},
    { programa_Id: 2, programa: "INCORPORA"},
    { programa_Id: 3, programa: "SENDOTU"},
    { programa_Id: 4, programa: "EMARI"},
    { programa_Id: 5, programa: "ELKARREKIN"},
    { programa_Id: 6, programa: "AURRERA"},
    { programa_Id: 7, programa: "BIDEAN"},
    { programa_Id: 8, programa: "EGUNEKO ZENTRO"},
]

export const centros = [
    { centro_Id: 1, centro: "AMARA"},
    { centro_Id: 2, centro: "MARTUTENE 12"},
    { centro_Id: 3, centro: "MARTUTENE 30"},
    { centro_Id: 4, centro: "EXTERIOR"},
]
